'use client';

import {FormEvent,useEffect,useRef,useState} from 'react';
import {Map as MapLibreMap,Marker as MapLibreMarker,NavigationControl,ScaleControl} from 'maplibre-gl';
import type {Map as MLMap,Marker} from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {AlertTriangle,Bell,Camera,ChevronRight,CloudRain,ExternalLink,Layers,LocateFixed,MapPin,Plane,Radio,RefreshCw,Rss,Search,ShieldAlert,Ship,Sun,Wind,X} from 'lucide-react';

type Flight={icao:string;callsign:string;country:string;lon:number;lat:number;altitude:number|null;ground:boolean;velocity:number|null;heading:number|null;verticalRate:number|null;squawk:string|null};
type Cam={id:string;name:string;lat:number;lon:number;image:string;video:string;view?:string;available:boolean;source:string};
type Crime={city:string;lat:number;lon:number;count:number;month:string;topCategory:string;topCount:number;note:string};
type News={title:string;link:string;date:string;region:string};type Social={id:string;date:string;url:string;text:string;author:string;network:string;verified:false};
type Selection={kind:'flight';data:Flight}|{kind:'camera';data:Cam}|{kind:'crime';data:Crime}|null;
const street={version:8 as const,sources:{osm:{type:'raster' as const,tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster' as const,source:'osm'}]};
const satellite={version:8 as const,sources:{sat:{type:'raster' as const,tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'Tiles © Esri'}},layers:[{id:'sat',type:'raster' as const,source:'sat'}]};
const radio=[['BBC Radio 1',51.518,-.143,'live:bbc_radio_one'],['BBC Radio 2',51.518,-.143,'live:bbc_radio_two'],['BBC Radio 4',51.518,-.143,'live:bbc_radio_fourfm'],['BBC London',51.507,-.128,'live:bbc_london'],['BBC Manchester',53.481,-2.243,'live:bbc_radio_manchester'],['BBC Merseyside',53.408,-2.991,'live:bbc_radio_merseyside'],['BBC Leeds',53.801,-1.549,'live:bbc_radio_leeds'],['BBC Sheffield',53.381,-1.47,'live:bbc_radio_sheffield'],['BBC Newcastle',54.978,-1.617,'live:bbc_radio_newcastle'],['BBC Cumbria',54.89,-2.944,'live:bbc_radio_cumbria'],['BBC WM',52.486,-1.89,'live:bbc_wm'],['BBC Bristol',51.454,-2.588,'live:bbc_radio_bristol'],['BBC Cornwall',50.263,-5.052,'live:bbc_radio_cornwall'],['BBC Devon',50.718,-3.533,'live:bbc_radio_devon'],['BBC Solent',50.91,-1.404,'live:bbc_radio_solent'],['BBC Kent',51.279,.521,'live:bbc_radio_kent'],['BBC Scotland',55.858,-4.259,'live:bbc_radio_scotland_fm'],['BBC nan Gàidheal',57.478,-4.224,'live:bbc_radio_nan_gaidheal'],['BBC Wales',51.481,-3.181,'live:bbc_radio_wales_fm'],['BBC Cymru',52.414,-4.081,'live:bbc_radio_cymru'],['BBC Ulster',54.597,-5.93,'live:bbc_radio_ulster'],['BBC Foyle',55.006,-7.319,'live:bbc_radio_foyle']].map(r=>[r[0],r[1],r[2],`https://www.bbc.co.uk/sounds/play/${r[3]}`]);

export default function Home(){
 const host=useRef<HTMLDivElement>(null),map=useRef<MLMap|null>(null),markers=useRef<Marker[]>([]);
 const [flights,setFlights]=useState<Flight[]>([]),[cameras,setCameras]=useState<Cam[]>([]),[selection,setSelection]=useState<Selection>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [flightOn,setFlightOn]=useState(true),[camOn,setCamOn]=useState(true),[radioOn,setRadioOn]=useState(true),[crimeOn,setCrimeOn]=useState(true),[base,setBase]=useState<'street'|'satellite'>('street'),[query,setQuery]=useState('');
 const [news,setNews]=useState<News[]>([]),[social,setSocial]=useState<Social[]>([]),[crimes,setCrimes]=useState<Crime[]>([]);
 const [weather,setWeather]=useState<{temperature_2m:number;wind_speed_10m:number;weather_code:number}|null>(null),[updated,setUpdated]=useState<Date|null>(null);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/feeds');if(!r.ok)throw new Error();const d=await r.json();setFlights(d.flights||[]);setCameras(d.cameras||[]);setError(d.errors?.join(' · ')||'');setUpdated(new Date(d.updatedAt));}catch{setError('Live feeds could not be reached. Retrying automatically.')}finally{setLoading(false)}};
 const loadIntel=async()=>{try{const r=await fetch('/api/intel');if(!r.ok)throw new Error();const d=await r.json();setNews(d.news||[]);setSocial(d.social||[]);setCrimes(d.crime||[]);}catch{setError(x=>x||'Intelligence feeds are partially unavailable.')}};
 const weatherAt=async(lat:number,lon:number)=>{try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat.toFixed(3)}&longitude=${lon.toFixed(3)}&current=temperature_2m,weather_code,wind_speed_10m`);const d=await r.json();setWeather(d.current);}catch{}};
 useEffect(()=>{if(!host.current)return;const m=new MapLibreMap({container:host.current,style:street,center:[-2.7,54.6],zoom:5.25,maxZoom:18,minZoom:4});m.addControl(new NavigationControl({showCompass:true}),'bottom-right');m.addControl(new ScaleControl({unit:'metric'}),'bottom-left');m.on('load',()=>weatherAt(54.6,-2.7));m.on('moveend',()=>{const c=m.getCenter();weatherAt(c.lat,c.lng)});map.current=m;return()=>m.remove()},[]);
 useEffect(()=>{map.current?.setStyle(base==='street'?street:satellite)},[base]);
 useEffect(()=>{load();loadIntel();const fast=setInterval(load,60000),slow=setInterval(loadIntel,120000);return()=>{clearInterval(fast);clearInterval(slow)}},[]);
 useEffect(()=>{markers.current.forEach(m=>m.remove());markers.current=[];if(!map.current)return;
   if(flightOn)flights.forEach(f=>{const el=document.createElement('button');el.className='map-marker aircraft';el.title=`Flight ${f.callsign}`;el.innerHTML='<span>✈</span>';el.style.transform=`rotate(${f.heading||0}deg)`;el.onclick=()=>setSelection({kind:'flight',data:f});markers.current.push(new MapLibreMarker({element:el}).setLngLat([f.lon,f.lat]).addTo(map.current!))});
   if(camOn)cameras.forEach(c=>{const el=document.createElement('button');el.className='map-marker camera';el.title=c.name;el.innerHTML='<span>●</span>';el.onclick=()=>setSelection({kind:'camera',data:c});markers.current.push(new MapLibreMarker({element:el}).setLngLat([c.lon,c.lat]).addTo(map.current!))});
   if(radioOn)radio.forEach(r=>{const el=document.createElement('button');el.className='map-marker radio';el.title=r[0] as string;el.innerHTML='<span>◉</span>';el.onclick=()=>window.open(r[3] as string,'_blank');markers.current.push(new MapLibreMarker({element:el}).setLngLat([r[2] as number,r[1] as number]).addTo(map.current!))});
   if(crimeOn)crimes.forEach(c=>{const el=document.createElement('button');el.className='map-marker crime';el.title=`${c.city} police data`;el.innerHTML='<span>!</span>';el.onclick=()=>setSelection({kind:'crime',data:c});markers.current.push(new MapLibreMarker({element:el}).setLngLat([c.lon,c.lat]).addTo(map.current!))});
 },[flights,cameras,crimes,flightOn,camOn,radioOn,crimeOn]);
 const search=async(e:FormEvent)=>{e.preventDefault();if(!query.trim()||!map.current)return;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&countrycodes=gb&limit=1&q=${encodeURIComponent(query)}`);const d=await r.json();if(d[0])map.current.flyTo({center:[+d[0].lon,+d[0].lat],zoom:12,essential:true});}catch{setError('Location search is temporarily unavailable.')}};
 return <main className="app">
  <header className="mast"><div className="logo"><span>U<span>K</span></span><div><b>SENTINEL UK</b><small>OPEN DATA COMMAND</small></div></div><form onSubmit={search}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search any UK town, postcode or landmark"/><button>Locate</button></form><div className="live"><i/>LIVE DATA <strong>{updated?.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})||'CONNECTING'}</strong></div></header>
  <section className="body"><aside className="rail"><div className="rail-head"><span>MAP LAYERS</span><Layers size={15}/></div>
    <Layer icon={<Plane/>} color="#f59e0b" label="Live aircraft" count={flights.length} on={flightOn} toggle={()=>setFlightOn(!flightOn)}/>
    <Layer icon={<Camera/>} color="#10b981" label="UK public cameras" count={cameras.length} on={camOn} toggle={()=>setCamOn(!camOn)}/>
    <Layer icon={<Radio/>} color="#a78bfa" label="Radio stations" count={radio.length} on={radioOn} toggle={()=>setRadioOn(!radioOn)}/>
    <Layer icon={<ShieldAlert/>} color="#ef4444" label="Police data" count={crimes.length} on={crimeOn} toggle={()=>setCrimeOn(!crimeOn)}/>
    <Layer icon={<Ship/>} color="#38bdf8" label="AIS vessels" count="API" on={false} disabled toggle={()=>{}}/>
    <div className="source-note"><b>REAL FEEDS</b><p>OpenSky aircraft plus TfL and TrafficWatchNI cameras refresh every 60 seconds.</p><button onClick={()=>map.current?.flyTo({center:[-5.93,54.6],zoom:11})}>Jump to Belfast →</button></div>
    <div className="weather-card"><div><span>MAP CENTRE</span>{weather&&weather.weather_code<3?<Sun/>:<CloudRain/>}</div><strong>{weather?`${Math.round(weather.temperature_2m)}°C`:'—'}</strong><p><Wind size={13}/>{weather?`${Math.round(weather.wind_speed_10m)} km/h wind`:'Loading weather'}</p><small>Open-Meteo · live model</small></div>
    <button className="alert-enable" onClick={()=>{'Notification' in window&&Notification.requestPermission()}}><Bell/>ENABLE DESKTOP ALERTS</button>
    <div className="health"><span><i className={error?'warn':''}/>{error?'PARTIAL SERVICE':'ALL SYSTEMS LIVE'}</span><button onClick={load}><RefreshCw className={loading?'spin':''} size={14}/></button></div>
  </aside>
  <section className="map-area"><div ref={host} className="real-map"/><div className="map-top"><div className="basemap"><button className={base==='street'?'active':''} onClick={()=>setBase('street')}>STREET</button><button className={base==='satellite'?'active':''} onClick={()=>setBase('satellite')}>SATELLITE</button></div><button className="home" onClick={()=>map.current?.flyTo({center:[-2.7,54.6],zoom:5.25})}><LocateFixed size={15}/>FULL UK</button></div>
    {loading&&flights.length===0&&<div className="loading"><RefreshCw className="spin"/>Connecting to live UK feeds…</div>}
    {selection&&<Detail selection={selection} close={()=>setSelection(null)}/>}<div className="legend"><span><i className="air"/>Aircraft</span><span><i className="cam"/>Traffic camera</span><span><i className="rad"/>Radio</span><b>{flights.length+cameras.length} LIVE OBJECTS</b></div>
  </section>
  <aside className="intel"><div className="intel-title"><span>UK INTELLIGENCE STREAM</span><em>LIVE / 120s</em></div><div className="metrics"><div><Plane/><span><b>{flights.length}</b>aircraft</span></div><div><Camera/><span><b>{cameras.length}</b>cameras</span></div></div>
    <h3><Rss/> LIVE NEWS · ALL NATIONS</h3><div className="news-stream">{news.slice(0,9).map((n,i)=><a href={n.link} target="_blank" key={`${n.link}-${i}`}><span>{n.region}</span><b>{n.title}</b><small>{new Date(n.date).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}<ExternalLink/></small></a>)}</div>
    <h3>SOCIAL PULSE · UNVERIFIED</h3><div className="social-stream">{social.slice(0,7).map(s=><a href={s.url} target="_blank" key={s.id}><span>@ {s.author}</span><p>{s.text}</p><small>{s.network} · public post</small></a>)}</div>
    <h3>POLICE DATA · LATEST MONTH</h3><div className="crime-list">{crimes.map(c=><button key={c.city} onClick={()=>{setSelection({kind:'crime',data:c});map.current?.flyTo({center:[c.lon,c.lat],zoom:10})}}><ShieldAlert/><span><b>{c.city}</b><small>{c.count.toLocaleString()} records · {c.month}</small></span><ChevronRight/></button>)}</div>
    <div className="maritime"><Ship/><div><b>LIVE VESSEL SOURCE FOUND</b><p>AISStream offers free live AIS. A private API key and secure WebSocket relay are required before boats can be shown safely.</p><a href="https://aisstream.io" target="_blank">Connect AISStream →</a></div></div>
    <div className="legal"><AlertTriangle/><p><b>Responsible public-data system</b>Crime locations are anonymised monthly police data. Social posts are unverified and never geolocated. No private-device discovery or personal tracking.</p></div>
  </aside></section>
  <footer className="news-ticker"><strong>BREAKING UK</strong><div>{news.slice(0,12).map((n,i)=><span key={i}><b>{n.region}</b> {n.title}<i>◆</i></span>)}</div><em>{error||'ALL FEEDS OPERATIONAL'}</em></footer>
 </main>
}

function Layer({icon,color,label,count,on,toggle,disabled=false}:{icon:React.ReactNode;color:string;label:string;count:number|string;on:boolean;toggle:()=>void;disabled?:boolean}){return <button className={`layer ${on?'on':''} ${disabled?'disabled':''}`} onClick={toggle} disabled={disabled}><span style={{color}}>{icon}</span><div><b>{label}</b><small>{disabled?'Provider key required':'Public live feed'}</small></div><strong>{count}</strong><i/></button>}
function Detail({selection,close}:{selection:NonNullable<Selection>;close:()=>void}){if(selection.kind==='camera'){const c=selection.data;return <article className="detail camera-detail"><button className="close" onClick={close}><X/></button><div className="video">{c.video?<video key={c.video} src={c.video} autoPlay muted loop playsInline poster={c.image}/>:<img src={c.image} alt={`Latest view from ${c.name}`}/>}<span><i/>LIVE · {c.source.toUpperCase()}</span></div><div className="detail-copy"><small>PUBLIC TRAFFIC CAMERA</small><h2>{c.name}</h2><p><MapPin/>{c.source} · {c.view||'Road view'}</p><div><span>STATUS <b>{c.available?'AVAILABLE':'OFFLINE'}</b></span><span>REFRESH <b>~5 MIN</b></span></div><a href={c.video||c.image} target="_blank">Open source image <ChevronRight/></a></div></article>}if(selection.kind==='crime'){const c=selection.data;return <article className="detail crime-detail"><button className="close" onClick={close}><X/></button><div className="flight-hero crime-hero"><ShieldAlert/><span>POLICE.UK · MONTHLY DATA</span></div><div className="detail-copy"><small>ANONYMISED AREA SUMMARY</small><h2>{c.city}</h2><p>{c.month} · approximate locations</p><div><span>RECORDS <b>{c.count.toLocaleString()}</b></span><span>TOP CATEGORY <b>{c.topCategory.replaceAll('-',' ')}</b></span></div><small>{c.note||'Not a live incident feed. Locations are anonymised by Police.uk.'}</small></div></article>}const f=selection.data;return <article className="detail flight-detail"><button className="close" onClick={close}><X/></button><div className="flight-hero"><Plane style={{transform:`rotate(${f.heading||0}deg)`}}/><span>LIVE ADS-B POSITION</span></div><div className="detail-copy"><small>AIRCRAFT · {f.icao.toUpperCase()}</small><h2>{f.callsign||'Unknown callsign'}</h2><p>{f.country}</p><div><span>ALTITUDE <b>{f.altitude?`${Math.round(f.altitude*3.28084).toLocaleString()} FT`:'GROUND'}</b></span><span>SPEED <b>{f.velocity?`${Math.round(f.velocity*1.94384)} KT`:'—'}</b></span><span>HEADING <b>{f.heading?`${Math.round(f.heading)}°`:'—'}</b></span><span>SQUAWK <b>{f.squawk||'—'}</b></span></div><small>Position supplied by OpenSky Network</small></div></article>}
