type NewsItem={title:string;link:string;date:string;region:string};
const feeds=[['UK','https://feeds.bbci.co.uk/news/uk/rss.xml'],['England','https://feeds.bbci.co.uk/news/england/rss.xml'],['Scotland','https://feeds.bbci.co.uk/news/scotland/rss.xml'],['Wales','https://feeds.bbci.co.uk/news/wales/rss.xml'],['Northern Ireland','https://feeds.bbci.co.uk/news/northern_ireland/rss.xml']] as const;
const cities=[['London',51.5074,-.1278],['Belfast',54.5973,-5.9301],['Cardiff',51.4816,-3.1791],['Manchester',53.4808,-2.2426],['Birmingham',52.4862,-1.8904],['Edinburgh',55.9533,-3.1883]] as const;
const clean=(s:string)=>s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const tag=(xml:string,name:string)=>clean(xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]||'');

async function news(signal:AbortSignal){const results=await Promise.allSettled(feeds.map(async([region,url])=>{const r=await fetch(url,{signal});if(!r.ok)throw new Error();const xml=await r.text();return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,7).map(m=>({title:tag(m[1],'title'),link:tag(m[1],'link'),date:tag(m[1],'pubDate'),region}))}));return results.flatMap(r=>r.status==='fulfilled'?r.value:[]).sort((a,b)=>+new Date(b.date)-+new Date(a.date)).slice(0,24)}
async function crimes(signal:AbortSignal){const results=await Promise.allSettled(cities.map(async([city,lat,lon])=>{const r=await fetch(`https://data.police.uk/api/crimes-street/all-crime?lat=${lat}&lng=${lon}`,{signal});if(!r.ok)throw new Error();const data=await r.json() as Array<{category:string;month:string}>;const counts:Record<string,number>={};data.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];return{city,lat,lon,count:data.length,month:data[0]?.month||'',topCategory:top?.[0]||'none',topCount:top?.[1]||0,note:city==='Edinburgh'?'British Transport Police data only':''}}));return results.flatMap(r=>r.status==='fulfilled'?[r.value]:[])}
async function social(signal:AbortSignal){const r=await fetch('https://mastodon.social/api/v1/timelines/tag/uk?limit=14',{signal,headers:{'User-Agent':'UK-Signal/1.0'}});if(!r.ok)return[];const data=await r.json() as Array<{id:string;created_at:string;url:string;content:string;account:{display_name:string;acct:string}}>;return data.map(x=>({id:x.id,date:x.created_at,url:x.url,text:clean(x.content).slice(0,240),author:x.account.display_name||x.account.acct,network:'Mastodon #UK',verified:false})).filter(x=>x.text)}
export async function GET(){const signal=AbortSignal.timeout(14000);const [n,c,s]=await Promise.allSettled([news(signal),crimes(signal),social(signal)]);return Response.json({news:n.status==='fulfilled'?n.value:[],crime:c.status==='fulfilled'?c.value:[],social:s.status==='fulfilled'?s.value:[],updatedAt:new Date().toISOString(),maritime:{provider:'AISStream',status:'key_required',message:'Free API key and secure backend relay required for live UK vessel positions.'}},{headers:{'Cache-Control':'public, max-age=60, s-maxage=120'}})}
