type NewsItem={title:string;link:string;date:string;region:string};
const feeds=[['UK','https://feeds.bbci.co.uk/news/uk/rss.xml'],['England','https://feeds.bbci.co.uk/news/england/rss.xml'],['Scotland','https://feeds.bbci.co.uk/news/scotland/rss.xml'],['Wales','https://feeds.bbci.co.uk/news/wales/rss.xml'],['Northern Ireland','https://feeds.bbci.co.uk/news/northern_ireland/rss.xml']] as const;
const cities=[['London',51.5074,-.1278],['Belfast',54.5973,-5.9301],['Cardiff',51.4816,-3.1791],['Manchester',53.4808,-2.2426],['Birmingham',52.4862,-1.8904],['Edinburgh',55.9533,-3.1883]] as const;
const clean=(s:string)=>s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const tag=(xml:string,name:string)=>clean(xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]||'');

async function news(signal:AbortSignal){const results=await Promise.allSettled(feeds.map(async([region,url])=>{const r=await fetch(url,{signal});if(!r.ok)throw new Error();const xml=await r.text();return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,7).map(m=>({title:tag(m[1],'title'),link:tag(m[1],'link'),date:tag(m[1],'pubDate'),region}))}));return results.flatMap(r=>r.status==='fulfilled'?r.value:[]).sort((a,b)=>+new Date(b.date)-+new Date(a.date)).slice(0,24)}
async function crimes(signal:AbortSignal){const results=await Promise.allSettled(cities.map(async([city,lat,lon])=>{const r=await fetch(`https://data.police.uk/api/crimes-street/all-crime?lat=${lat}&lng=${lon}`,{signal});if(!r.ok)throw new Error();const data=await r.json() as Array<{category:string;month:string}>;const counts:Record<string,number>={};data.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];return{city,lat,lon,count:data.length,month:data[0]?.month||'',topCategory:top?.[0]||'none',topCount:top?.[1]||0,note:city==='Edinburgh'?'British Transport Police data only':''}}));return results.flatMap(r=>r.status==='fulfilled'?[r.value]:[])}
async function social(signal:AbortSignal){const r=await fetch('https://mastodon.social/api/v1/timelines/tag/uk?limit=14',{signal,headers:{'User-Agent':'UK-Signal/1.0'}});if(!r.ok)return[];const data=await r.json() as Array<{id:string;created_at:string;url:string;content:string;account:{display_name:string;acct:string}}>;return data.map(x=>({id:x.id,date:x.created_at,url:x.url,text:clean(x.content).slice(0,240),author:x.account.display_name||x.account.acct,network:'Mastodon #UK',verified:false})).filter(x=>x.text)}
async function pagers(signal:AbortSignal){const r=await fetch('https://112-nu.nl/hulpdiensten/rss',{signal,headers:{'User-Agent':'DAVENET/1.0'}});if(!r.ok)throw new Error();const xml=await r.text();return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,18).map(m=>({id:tag(m[1],'guid')||tag(m[1],'link'),title:tag(m[1],'title'),message:tag(m[1],'description'),service:tag(m[1],'category')||'P2000',link:tag(m[1],'link'),date:tag(m[1],'pubDate'),network:'P2000 Netherlands'})).filter(x=>x.title&&x.link)}
async function risk(signal:AbortSignal){
 const [threatResult,weatherResult,floodResult,quakeResult]=await Promise.allSettled([
  fetch('https://www.gov.uk/terrorism-national-emergency',{signal,headers:{'User-Agent':'UK-Sentinel/1.0'}}).then(r=>r.ok?r.text():Promise.reject()),
  fetch('https://weather.metoffice.gov.uk/public/data/PWSCache/WarningsRSS/Region/UK',{signal}).then(r=>r.ok?r.text():Promise.reject()),
  fetch('https://environment.data.gov.uk/flood-monitoring/id/floods?min-severity=3',{signal}).then(r=>r.ok?r.json():Promise.reject()),
  fetch('http://earthquakes.bgs.ac.uk/feeds/MhSeismology.xml',{signal}).then(r=>r.ok?r.text():Promise.reject())
 ]);
 const threatHtml=threatResult.status==='fulfilled'?clean(threatResult.value):'';
 const national=threatHtml.match(/threat to the UK[^.]{0,180}\b(low|moderate|substantial|severe|critical)\b/i)?.[1]?.toUpperCase()||'SEVERE';
 const northernIreland=threatHtml.match(/Northern Ireland-related[^.]{0,180}\b(low|moderate|substantial|severe|critical)\b/i)?.[1]?.toUpperCase()||'SUBSTANTIAL';
 const wx=weatherResult.status==='fulfilled'?[...weatherResult.value.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>({title:tag(m[1],'title'),description:tag(m[1],'description'),link:tag(m[1],'link'),date:tag(m[1],'pubDate')})).slice(0,12):[];
 const floodJson=floodResult.status==='fulfilled'?floodResult.value as {items?:Array<{floodAreaID:string;description:string;eaAreaName:string;severity:string;severityLevel:number;message:string;timeMessageChanged:string;floodArea?:{county?:string;riverOrSea?:string}}>}:{items:[]};
 const floods=(floodJson.items||[]).map(x=>({id:x.floodAreaID,title:x.description,area:x.floodArea?.county||x.eaAreaName,severity:x.severity,level:x.severityLevel,message:clean(x.message).slice(0,320),date:x.timeMessageChanged,river:x.floodArea?.riverOrSea||''}));
 const quakes=quakeResult.status==='fulfilled'?[...quakeResult.value.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>{const body=m[1],description=tag(body,'description');return{title:tag(body,'title').replace(/^UK Earthquake alert\s*:\s*/i,''),description,link:tag(body,'link').replace(/^http:/,'https:'),date:tag(body,'pubDate'),lat:+tag(body,'geo:lat'),lon:+tag(body,'geo:long'),magnitude:+(description.match(/Magnitude:\s*([\d.]+)/i)?.[1]||0)}}).slice(0,16):[];
 return{threat:{national,northernIreland,meaning:national==='CRITICAL'?'Attack highly likely in the near future':national==='SEVERE'?'Attack highly likely':national==='SUBSTANTIAL'?'Attack likely':national==='MODERATE'?'Attack possible but not likely':'Attack highly unlikely',source:'GOV.UK / JTAC'},weatherWarnings:wx,floods,earthquakes:quakes};
}
export async function GET(){const signal=AbortSignal.timeout(14000);const [n,c,s,p,riskResult]=await Promise.allSettled([news(signal),crimes(signal),social(signal),pagers(signal),risk(signal)]);return Response.json({news:n.status==='fulfilled'?n.value:[],crime:c.status==='fulfilled'?c.value:[],social:s.status==='fulfilled'?s.value:[],pagers:p.status==='fulfilled'?p.value:[],risk:riskResult.status==='fulfilled'?riskResult.value:{threat:{national:'UNKNOWN',northernIreland:'UNKNOWN',meaning:'Official source unavailable',source:'GOV.UK / JTAC'},weatherWarnings:[],floods:[],earthquakes:[]},updatedAt:new Date().toISOString(),maritime:{provider:'AISStream',status:'key_required',message:'Free API key and secure backend relay required for live UK vessel positions.'}},{headers:{'Cache-Control':'public, max-age=30, s-maxage=45'}})}
